#pragma once

#include "shared/utils/build_config.h"

typedef enum {
    BTN_LEFT = 0,
    BTN_RIGHT,
    BTN_UP,
    BTN_DOWN,
    BTN_INTERACT,
    BTN_LIFT,
    BTN_MOUSE_L,
    BTN_MOUSE_R,
#if DEBUG_BUILD
    BTN_ASSET_DEBUG_PRINT,
    BTN_DEBUG_COLLIDER_ECS,
    BTN_DEBUG_COLLIDER_PHYSICS,
    BTN_DEBUG_COLLIDER_STATIC,
    BTN_DEBUG_TRIGGERS,
    BTN_DEBUG_INSPECT,
    BTN_DEBUG_RELOAD_TMX,
    BTN_DEBUG_FPS,
    BTN_DEBUG_TRACE_START,
    BTN_DEBUG_TRACE_STOP,
#endif
    BTN_COUNT
} button_t;
